- name: Test Notify slack
  on:
    pull_request:
      branches:
        - '**'
  jobs:
    notify:
      name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C1234567890\",\"text\":\"Hello world from github\"}'