name: 'Task from PR body'
description: 'A action that get task from pull request body'
author: 'Francisco Cerdas'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: false
outputs:
  task:
    description: 'The task to output'
branding:
  icon: 'book-open'
  color: 'green'
runs:
  using: 'node12'
  main: 'dist/index.js'