name: Test Notify slack
on:
  pull_request:
    branches:
      - '**'
jobs:
  notify:
    runs-on: ubuntu-latest
    needs: [tasks]
    steps:
    - name: Task from PR body
      id: task
      uses: chicus12/github-action-get-jira-task@main

    - uses: pullreminders/slack-action@master
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"text\":\"${{ steps.task.outputs.task }}\"}'
