name: Test Notify slack
on:
  pull_request:
    types: [opened]
    branches:
      - '**'
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: pullreminders/slack-action@master
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"text\":\"Hello world from github\"}'
